/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pawtropoliss;

import pawtropoliss.controller.game.GameController;

public class App {

    public static void main(String[] args) {GameController.getInstance().playGame();
    }
}
