/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.project.pawtropoliss;


import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;


@SpringBootTest
public class PawtropolisApplicationTest {
    @Test
    void contextLoads() {
    }

}
