version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bruce
      POSTGRES_DB: pawtropolisProd
    ports:
      - "5433:5432"
    volumes:
      - ./creation.sql:/docker-entrypoint-initdb.d/creation.sql
