/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.project.pawtropoliss;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PawtropolisApplication {
    public static void main(String[] args) {
        SpringApplication.run(PawtropolisApplication.class, args);
    }
}
